import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const poppinsFont = Poppins({
  subsets: ["latin"],
  // Optional: Define a CSS variable for font customization
  weight: "400", // Optional: Specify font weight
  // ... other options
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppinsFont.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
